M48
; DRILL file {KiCad 9.0.3+dfsg-1} date 2026-05-09T19:23:00-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-09T19:23:00-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X212.883Y-110.679
X218.663Y-110.679
T2
X205.74Y-88.265
X205.74Y-114.935
M30
